#!/bin/bash

echo "🚀 Deploying TradeSphere.ai to Render.com..."
echo ""

echo "📋 Please follow these steps:"
echo ""
echo "1. Go to https://render.com and sign up with GitHub"
echo "2. Click 'New' → 'Web Service'"
echo "3. Connect your GitHub repository: mikhailsal123/PennApps-Project"
echo "4. Configure the service:"
echo "   - Name: tradesphere-backend"
echo "   - Environment: Python 3"
echo "   - Build Command: pip install -r requirements.txt"
echo "   - Start Command: python3 app.py"
echo "   - Add Environment Variable: FLASK_ENV=production"
echo "5. Click 'Create Web Service'"
echo "6. Wait for deployment to complete"
echo "7. Copy the generated URL (something like https://tradesphere-backend.onrender.com)"
echo ""
echo "🔧 After deployment, run this command to update the frontend:"
echo "   ./update-frontend-url.sh YOUR_RENDER_URL"
echo ""
echo "📖 For detailed instructions, see RENDER_DEPLOYMENT.md"
