#!/bin/bash

echo "🚀 Deploying Next.js Frontend to Render.com..."
echo ""

echo "📋 Please follow these steps:"
echo ""
echo "1. Go to https://render.com and sign up with GitHub"
echo "2. Click 'New' → 'Web Service'"
echo "3. Connect your GitHub repository: mikhailsal123/PennApps-Project"
echo "4. Configure the service:"
echo "   - Name: tradesphere-frontend"
echo "   - Environment: Node"
echo "   - Build Command: cd frontend && npm ci && npm run build"
echo "   - Start Command: cd frontend && npm start"
echo "   - Add Environment Variable: NODE_ENV=production"
echo "5. Click 'Create Web Service'"
echo "6. Wait for deployment to complete"
echo "7. Copy the generated URL (something like https://tradesphere-frontend.onrender.com)"
echo ""
echo "🔧 After deployment, your Next.js app will be live on Render!"
echo "📖 For detailed instructions, see RENDER_FRONTEND_DEPLOYMENT.md"
