services:
  - type: web
    name: tradesphere-backend
    env: python
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: python3 app.py
    envVars:
      - key: FLASK_ENV
        value: production
      - key: PORT
        value: 10000
